# 项目相关配置
ruoyi:
  # 名称
  name: MedicalCare
  # 版本
  version: 3.8.4
  # 版权年份
  copyrightYear: 2022
  # 实例演示开关
  demoEnabled: true
#   文件路径 示例（ Windows配置D:/medical/uploadPath，Linux配置 /home/medical/uploadPath）
  profile: E:/走旺运(全)/上传图片
#  profile: /home/medical/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8088
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: warn

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 10
    # 密码锁定时间（默认10分钟）
    lockTime: 10

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: druid
  # 文件上传
  servlet:
     multipart:
       # 单个文件大小
       max-file-size:  100MB
       # 设置总上传的文件大小
       max-request-size:  500MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 地址
#    host: localhost
    host: 42.51.3.108
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
#    password:
    password: qwerasdf
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# token配置
token:
    # 令牌自定义标识
    header: authorization
    # 令牌密钥
    secret: abcdefghijklmnopqrstuvwxyz
    # 令牌有效期（默认30分钟）(单位：分钟)
    expireTime: 12000

# MyBatis配置
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.ruoyi.project.**.domain
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath*:mybatis/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml
##   配置下划线转驼峰
#    configuration: map-underscore-to-camel-case=true
    #下划线转驼峰
    configuration:
      map-underscore-to-camel-case: true
# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping:

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*,/login_connect/*

# 代码生成
gen:
  # 作者
  author: ruoyi
  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool
  packageName: com.ruoyi.project.area
  # 自动去除表前缀，默认是true
  autoRemovePre: false
  # 表前缀（生成类名不会包含表前缀，多个用逗号分隔）
  tablePrefix: sys_


push:
  appId: 1pZqByza0U6nh7rurxfUJA
  appKey: CkDL497sJc9heC5e4BnWaA
  masterSecret: Hk01j9hXAx7H30fWPNzY78
  appSecret: fgjOuj9DzF9JQbbC9LIbd8



pay:
    #微信支付
    wechatPay:
      app-id: wx74862e0dfcf69954
      api-v3-key: UDuLFDcmy5Eb6o0nTNZdu6ek4DDh4K8B
      mch-id: 1558950191
      mch-serial-no: 34345964330B66427E0D3D28826C4993C77E631F
      mch-private-key: src/main/resources/cert/apiclient_key.pem
#      mch-private-key: /home/medical/cert/apiclient_key.pem
      notify-domain: https://xxxx.com
    #支付宝支付
    aliPay:
      app-id: 2021000121696067
      seller-id: 2088621993891958
      mch-private-key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC8ZSKIx2uokKq9JPY2gJfrquOe1G12hjO4egNPiOSgKbCrBX2MnSKW88SE+FdSZbGKxmgWPiEAI5ewA1lwDdhTgP4tX1ji3BDyb4txGEYT2KPc7KxCSQCt8I9K2FXMPwfAZTWRBzNT59zMZBm37mgDdEgm1NSdSCtfGObhijXpISvqbK+srRR6aeRR146wKm+neGvKv6nZzMubMInLxvxeIOVKH27oZcL4TQNCf355mMglwlST0dxakVAV7CAawlMzZDYE8Q64vTa3jg7N2G1eCPDNdnrLTLUOFyWEM2gocLzrx1P48osJzcjVJyDK13QRo8oMm/DXMHLE0aOgTvLBAgMBAAECggEAV1zy2cjYZM/JTXLxdi7FxHR3n3TU2gy7uUVjeaN6mccbdQNTyDwqCSQ7sonTPJOJ9FezdvUSqpTWx7mV5P+WnIqJ1BKODo2MklAlsqlV/egNfOqHqyldVkvitwuBJfjoqFCGuZ1EMRmpa2LUBlZZB5kJyHATtGf+LNhIYLiN7XA3dyRKQQIA3WG1+0Qzaez5xYWw3CZRyIekg+3ZafDm17kmwBlvZ5dKayySxq1WbFsKc8fiI9rNyZThEC8R5NxcdJPdjOr29XyG71EhSzUyys5ZzCDMhaDLhysy9MBe9eMQaDpZFZj9kWKHMnNUrr+eDgt6raMydiAYPxP+ucI6jQKBgQDpQy4fu5H+k79wlaen/mC/oaJ4icgMPwAP9GSdeJkx8hR49qFlHVJ54At7xTSf7CdeB0BoHP/FFR2h760wrxZ6Oif6lTkH9Kde2syNaxXiNiE7V6Lk4PljRp5Y88NJtRNlgVSIOvved3Fwxs31Yq9scaSixHigD+EWOM8QnG5GawKBgQDOwlYpZkRJQ7uVIFD3XRX3IVOInO8bwcnrTqH2awgdL8LhsHYh+h+XnXl0Hx/qtdR8SCaUVK41qQM4clfRVzd9jafMvpE8rmhOYgheGMFDYPkzD0pCbQw9gQcuZUxYuPoCLxTR9YZPn4aiOb3yn4FFPv68Drc3IEqqnWk70zk+gwKBgQDRw6cbxDqy27zhisM9MGVijwEjMowibxkoP9enQIdLQe4lJWzYGDlN/it1f08mrWBtj0ndFo7vdWCzemydhiZJfjjrf/vMareEdnBSkEUaqyDRU6rZ9nJuU1gcmAE7LEooEtiotZpAYdsy1qTqEXe9pqit8s6i6gS5ThbvUi1cxwKBgFcr6kXUHzBAhWLvWBOixHMIMv7jI5CxWJ+D7JdHMwmTLHgY/QWAPjefJijGQp+jf+3SQanCNhzboEb5NntFaVjfE4MoSXWrFsENZfe+OiVdSlOzu5xb+5AmyU9PWCwD+SxYi0+mU7VYTdwxuhsEEu2ODLpe/fIZBEIA0fBuMrFfAoGBAJYImLyZduGpWosmaqc0zX+Ja84zQDMnor49VOKs3E06hAs4QWq2JemLMZPWQ51KA2MOUr4ePyu1kYOA7Qzu77v3JoCI1wd0uDfsfcPc21FSXDNfEnHzziMWQPFIZA6LCMPp/BF/9ZodCblMTaAT14cmjCrLnmal7qbJkdgGDh4v
      ali-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgIml4F7EzlnvKvIISPnVdr1b4iQIGD5snoCSW8P49qcNwAXRb5XfN3ho5CfWQsTLubYjhLQQHRO7Ds7ObkO6kEBcZfha1xsayBhMookzQYzANO0xKjwA9eVkFYuJQBm0AmjbX3y2xQqD6aQxxwZbFqzNDbftYxWqLMDDMLuQ3T8IPQRxUK28464B2fnpVbq2KkARy/Kyy5RjcGF7YC1Mo/btBZ0mDIxuHOK0+0qbyu/PK2rkkoteq4g3Kzac8nsfeQ5nWoLsOn6oRTv7ZMpxjESz3FsES07bKZN8hov8fZ3R0hnI7m9LKCZJnFvvXaFzZ8h+ePx8CdUxLOhP70n/hQIDAQAB
      gateway-url: https://openapi.alipaydev.com/gateway.do
      notify-url: http://localhost:8081/aliPayApi/payNotify




